# Generated by Django 5.2 on 2025-04-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_asset_user_alter_operation_user'),
    ]

    operations = [
    ]
