# Generated by Django 5.2 on 2025-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_asset_dividend_yeld_asset_pl_asset_pvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='dividend_yeld',
        ),
        migrations.AddField(
            model_name='asset',
            name='dividend_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pvp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
