# Generated by Django 5.2 on 2025-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_asset_dividend_yeld_asset_dividend_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
